### ISSUE TITLE
Optimizer not defined

### ISSUE THREAD

**Issue by freiburgermsu** [jump-dev/GLPK.jl#217]
Hello,

I receive that attached error 
![optimizer_error](https://user-images.githubusercontent.com/60083977/173082690-2611ce9c-8588-4b29-a844-cfccebc59c5f.JPG)
when I attempt to execute this Julia script
```julia
using Pkg
import GLPK, MathProgBase, COBRA
# include("$(Pkg.dir("COBRA"))/src/connect.jl")

mutable struct SolverConfig
    name      ::String
    handle
end

function build_LP(model)
    for i = 1:length(model.csense)
        if model.csense[i] == 'E'  model.csense[i] = '=' end
        if model.csense[i] == 'G'  model.csense[i] = '>' end
        if model.csense[i] == 'L'  model.csense[i] = '<' end
    end

    return MathProgBase.HighLevelInterface.buildlp(model.osense * model.c, model.S, model.csense, model.b, model.lb, model.ub, GLPK.Optimizer)
end

function execute_cobra(model_path)
    include("$(Pkg.dir("COBRA"))/config/solverCfg.jl")
    model = COBRA.loadModel(model_path, "S", "CMM_iAH991V2_iML1515.kb")
    
    solutionLP = MathProgBase.HighLevelInterface.solvelp(build_LP(model))

    # adapt the objective value
    if solutionLP.status == :Optimal
        solutionLP.objval = model.osense * solutionLP.objval
    end

    return solutionLP
end
```
Neither ``Optimizer`` class nor ``Optimizer`` function are recognized. How can the GLPK ``AbstractMathProgSolver`` object be properly called to pass in ``MathProgBase``? 

Thank you :)

**Comment by blegat** [comment]
You need to use https://github.com/JuliaOpt/GLPKMathProgInterface.jl to use GLPK with MathProgBase. Note that MathProgBase was deprecated in favor of MathOptInterface.

**Comment by odow** [comment]
* `Optimizer` isn't defined because you've installed an old version of GLPK.
 * You've installed an old version of GLPK because you're trying to use MathProgBase
 * MathProgBase is deprecated, and we don't encourage people to use it.

It seems like you're trying to use https://github.com/opencobra/COBRA.jl, but it seems like most of that code hasn't been updated for 3 years. I'd follow their documentation for using GLPK, it should still work, but you probably need something like `GLPKSolverLP()` instead of `GLPK.Optimizer`.


Closing because this isn't a bug in GLPK. If you have further questions, I'd open an issue in COBRA. If that doesn't help, you could post on the community forum, but we might not be able to help fix a package that hasn't been maintained for 3 years: https://discourse.julialang.org/c/domain/opt/13
